UserManagement/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using UserManagement.Data;
using UserManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace UserManagement.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly ApplicationDbContext _appDbContext;

        public DepartmentController(ILogger<DepartmentController> logger, ApplicationDbContext appDbContext)
        {
            
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AddDepartment()
        {
            return View();
        }

        public IActionResult SaveDepartment(Department department )
        {
            _appDbContext.Department.Add(department);
            _appDbContext.SaveChanges();
            return Redirect("AddDepartment");
        }
        public IActionResult GetDepartment(Department department)
        {
           List<Department> departmentList = _appDbContext.Department.ToList();
            return View(departmentList);
        }
        public IActionResult GetDepartmentById(int id)
        {
            // ViewBag.UserList = _appDbContext.User.ToList();
            Department department = _appDbContext.Department.Include(x => x.Users).FirstOrDefault(use => use.Id == id);
            return View(department);
        }
        public IActionResult UpdateDepartmentById(Department department)
        {
            _appDbContext.Department.Update(department);
            _appDbContext.SaveChanges();
            return RedirectToAction("GetDepartment");
        }
        public IActionResult DeleteDepartmentById(Department department)
        {
            //get user by id
            _appDbContext.Department.Remove(department);
            _appDbContext.SaveChanges();
            return RedirectToAction("GetDepartment");
        }

    }
}

UserManagement/Controllers/LogInController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UserManagement.Data;
using UserManagement.Models;
using UserManagement.ViewModels;

namespace UserManagement.Controllers
{
    
    public class LogInController : Controller
    {
        private readonly ApplicationDbContext _appDbContext;
        //manages user
        private readonly UserManager<IdentityUser> _userManager;
        //helps in signin process
        private readonly SignInManager<IdentityUser> _signInManager;
        //manages the role
        private readonly RoleManager<IdentityRole> _roleManager;
        public LogInController(ILogger<LogInController> logger, ApplicationDbContext appDbContext, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
        {

            _appDbContext = appDbContext;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult RegisterUser()
        {
            ViewBag.RoleList = _appDbContext.Roles.ToList();
            return View();
        }
        public async Task<IActionResult> SaveUser(RegisterViewModel registerViewModel)
        {
            var user = new IdentityUser()
            {
                UserName = registerViewModel.Email,
                Email = registerViewModel.Email
            };
            var userCreateResult = await _userManager.CreateAsync(user, registerViewModel.Password);
            if (userCreateResult.Succeeded)
            {
                var result = await _userManager.AddToRoleAsync(user, registerViewModel.RoleName);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                //handle error and display on register page
                foreach(var item in userCreateResult.Errors)
                {
                    //pass error on model to catch on view asp-validation-summary
                    ModelState.AddModelError(string.Empty, "Error"+item.Description);
                    //get role detail
                    ViewBag.RoleList = _appDbContext.Roles.ToList();
                    //return to same view
                    return View("RegisterUser", registerViewModel);
                }
                
            }
            //adding roles
            
            return RedirectToAction("RegisterUser");
        }
        public IActionResult LogInUser()
        {

            return View();
        }
        public async Task<IActionResult> LogInUsers(LoginViewModel logInViewModel)
        {
           
            var identityResult = await _signInManager.PasswordSignInAsync(logInViewModel.Email,
                logInViewModel.Password, false, false);
            if (identityResult.Succeeded)
            {
               
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("LogInUser");
        }
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("LogInUser");
        }
        // [Authorize(Roles ="admin")]
        public IActionResult AddRole()
        {
            return View();
        }

        public async Task<IActionResult> AddRoleDetail(RoleViewModel roleViewModel)
        {
            var role = new IdentityRole()
            {
                Name = roleViewModel.RoleName,
                
            };
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {               
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("AddRole");
        }

    }
}

// var user = _userManager.Users.ToList();
// calling users

UserManagement/Controllers/ShiftController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserManagement.Data;
using UserManagement.Models;

namespace UserManagement.Controllers
{
    public class ShiftController : Controller
    {
        private readonly ApplicationDbContext _appDbContext;

        public ShiftController(ILogger<ShiftController> logger, ApplicationDbContext appDbContext)
        {

            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddShift()
        {
            ViewBag.UserList = _appDbContext.User.ToList();
            return View();
        }
        public async Task<IActionResult> AddUserShift(UserShift user)
        {
            await _appDbContext.UserShift.AddAsync(user);
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("AddShift");
        }
        public IActionResult GetShift(UserShift shift)
        {
            List<UserShift> userShifts=_appDbContext.UserShift.ToList();
            //ViewBag.NameList = _appDbContext.User.ToList();
            return View(userShifts);
        }
        public IActionResult GetShiftyId(int id)
        {
            ViewBag.UserList = _appDbContext.User.ToList();
            //get user by id
            UserShift userShift = _appDbContext.UserShift.Find(id); 
            return View(userShift);
        }
        public IActionResult UpdateShiftById(UserShift userShift)
        {           
            _appDbContext.UserShift.Update(userShift);
            _appDbContext.SaveChanges();
            return RedirectToAction("GetShift");
        }
        public IActionResult DeleteShiftById(UserShift userShift)
        {
            _appDbContext.UserShift.Remove(userShift);
            _appDbContext.SaveChanges();
            return RedirectToAction("GetShift");
        }

    }
}

UserManagement/Controllers/ShiftStatusController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using UserManagement.Data;
using UserManagement.Models;
using UserManagement.ViewModels;

namespace UserManagement.Controllers
{
    public class ShiftStatusController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public ShiftStatusController(ApplicationDbContext applicationDbContext,
            UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _applicationDbContext = applicationDbContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetShiftStatus()
        {
            var logInUser = await _userManager.GetUserAsync(User);
            ViewBag.UserShiftStatus = new List<ShiftStatusViewModel>();
            if (logInUser != null)
            {
                var userDetail = _applicationDbContext.User
                    .Where(x => x.IdentityUserId == logInUser.Id).FirstOrDefault();
                if (userDetail != null)
                {
                    var userShiftId = _applicationDbContext.UserShift
                        .Where(x => x.UserId == userDetail.id).FirstOrDefault();
                    /*.Select(x => x.Id)*/
                    if (userShiftId!=null)
                    {
                        var userShiftLogId = _applicationDbContext.UserShiftLog
                        .Where(x => x.UserId == userDetail.id && x.UserShiftId==userShiftId.Id).FirstOrDefault();
                        ViewBag.UserShiftStatus = _applicationDbContext.UserShiftLog
                            .Where(x => x.UserId == userDetail.id && x.UserShiftId == userShiftId.Id)
                            .Select(x => new ShiftStatusViewModel
                            {
                                UserName = userDetail.name,
                                CheckInTime1 = x.CheckInTime.HasValue ? x.CheckInTime.Value.ToString("hh:mm tt"):null,
                                CheckOutTime1=x.CheckOutTime.HasValue? x.CheckOutTime.Value.ToString("hh:mm tt") :null,
                                AttendanceDate=x.CheckInTime.HasValue? x.CheckInTime.Value.ToString("dd/MM/yyyy"):null,
                                Shift = userShiftId.CheckIn.HasValue && userShiftId.CheckOut.HasValue ?
                                    userShiftId.CheckIn.Value.ToString("hh:mm tt") + "-" + userShiftId.CheckOut.Value.ToString("hh:mm tt") : null,
                                Status=x.CheckInTime.HasValue && x.CheckOutTime.HasValue? (x.CheckInTime.Value>userShiftId.CheckIn.Value.AddMinutes(15) 
                                    && x.CheckOutTime.Value< userShiftId.CheckOut.Value.AddMinutes(-15)?"late In early out"
                                    :x.CheckInTime.Value>userShiftId.CheckIn.Value.AddMinutes(15)?"late In"
                                    :x.CheckOutTime.Value<userShiftId.CheckOut.Value.AddMinutes(-15)?"early out"
                                    :"On Time")
                                    :"No Entry"
                            }) ;
                    }
                }

            }

            return View();
        }
        public async Task<IActionResult> LateInEarlyOut()
        {
            var logInUser = await _userManager.GetUserAsync(User);
            ViewBag.UserShiftStatus = new List<ShiftStatusViewModel>();
            if (logInUser != null)
            {
                var userDetail = _applicationDbContext.User
                    .Where(x => x.IdentityUserId == logInUser.Id).FirstOrDefault();
                if (userDetail != null)
                {
                    var param = new SqlParameter("@UserId", userDetail.id);
                    var result = _applicationDbContext.Sp_LateInEarlyOut_ViMo
                        .FromSqlRaw("[dbo].[Sp_LateInEarlyOut] @UserId", param).ToList();
                    ViewBag.UserShiftStatus=result;
                }

            }
            return View();
        }
    }
}

UserManagement/Views/Shared/_Layout.cshtml
@*refrencing to aspnet core identity*@
@using Microsoft.AspNetCore.Identity
@*//holds the sign in information, can be used to check user sign in detail*@
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UserManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(SignInManager.IsSignedIn(User)==true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddUser">Add User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetUser">View User List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="AddDepartment">Add Department</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="GetDepartment">View Department</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetUserInfo">User Informations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="AddRole">Add Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Shift" asp-action="AddShift">Add Shift</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Shift" asp-action="GetShift">Get Shift</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attandance" asp-action="Attandance">Track Attendance</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ShiftStatus" asp-action="GetShiftStatus">Shift Status</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ShiftStatus" asp-action="LateInEarlyOut">Shift Status SP</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="LogOut">Log_OUTS</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="RegisterUser">Register user</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="LogInUser">Log_In_user</a>
                            </li>
                        }
                        
                        
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UserManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>